### ISSUE TITLE
Look into Chrome and Chromedriver issues

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_flow#44]
https://github.com/teamcapybara/capybara/issues/2181#issuecomment-491306993

cc @edwardloveall

**Comment by edwardloveall** [comment]
I expect this will be resolved with a but update, but it's certainly frustrating at the moment.

**Comment by edwardloveall** [comment]
I looked into this more. We were getting an error from Selenium:

>session not created: Chrome version must be between 70 and 73

When I [upgraded the chromedriver binary](https://chromedriver.storage.googleapis.com/index.html) to 74.x or higher, it works.

If that's the fix you want I can put in a PR soon. I didn't just go for it because I'm wondering if we want support multiple versions of chromedriver which map to different versions of Chrome. It's kind of unpredictable when chrome will release new versions. There's also CI to consider.

**Comment by edwardloveall** [comment]
This also works as a fix: https://github.com/edwardloveall/lucky_bits/commit/2987d4182f85ecb26b204568d2d62206e0442f32

**Comment by paulcsmith** [comment]
Maybe we can change LuckyFlow to use the installed version of Chomedriver if it finds it. If not, then use the one that comes bundled with LuckyFlow. Just leaving this here as an idea to possibly tackle in the future
