### ISSUE TITLE
Migrate from Selenium to Marionette

### ISSUE THREAD

**Issue by watzon** [luckyframework/lucky_flow#57]
Just leaving this as a suggestion seeing as I just released the [first official version](https://github.com/watzon/marionette/releases/tag/0.1.0) of [Marionette](https://github.com/watzon/marionette).

Marionette should offer major speed and memory improvements over Selenium, since it's written in pure Crystal and doesn't rely on Java. It has the ability to attach to an active Firefox instance or launch one itself, which means that you could also watch the tests being preformed.

**Comment by paulcsmith** [comment]
LuckyFlow uses chromedriver which I think is fairly quick, but I am not sure how it compares to Marionette. What I think would be super cool is to have adapters like Capybara so that we can make one for Marionette and then you can use that or Chromedriver.

I imagine it would be something like this:

```crystal
abstract class LuckyFlow::Adapter
  abstract def start

  abstract def find_element
  abstract def click_element
end

class MarionetteAdapter < LuckyFlow::Adapter
  # Adapter specific settings
  Habitat.create do
    setting port : Int32
  end
end
```

This is of course missing a lot, but I think this general idea is the way to go. It might be a bit before I can get to something like this but I think it is definitely something LuckyFlow should do

**Comment by watzon** [comment]
I definitely plan on abstracting out the `Browser` class in the future to allow for multiple backends. I also really want to figure out a WebSockets workflow so that the DevTools protocol can be used instead of the marionette protocol. As it is I think chromedriver and geckodriver share most of the same API, so it may be possible to allow the use of both without too much trouble.

**Comment by watzon** [comment]
May as well update this issue too. I just added support for all WebDriver implementations across the board to Marionette, so with some tweaking it should be able to take over the job that Selenium is currently doing with ChromeDriver, as well as add support for GeckoDriver, OperaDriver, SafariDriver, and a lot more.

I'd be willing to look into seeing what it would take to migrate, but having looked through the issues I think it would close several.

**Comment by alexanderadam** [comment]
I certainly don't want to add more noise to this issue, but maybe integrating Playwright would be an useful alternative.

@naqvis [created a Shard](https://github.com/naqvis/playwright-cr#usage) for it (also referenced [in Microsoft's official documentation](https://github.com/microsoft/playwright/blob/master/docs/src/showcase.md#unofficial-language-ports)) and apart from [the 'regular' test web driver features](https://playwright.dev/docs/why-playwright) it also gives the possibility to [record a session](https://github.com/microsoft/playwright-cli#generate-code) and generate code out of it ([not yet for Crystal](https://github.com/microsoft/playwright-cli/issues/197), but it [doesn't seem too complicated](https://github.com/microsoft/playwright-cli/blob/master/src/codegen/languages/python.ts)).
Personally, I think "writing" specs for reproducing certain bugs is much easier if you just have to click the same things in the browser that the user clicked. It might give a huge productivity boost.

IMHO it's probably better to be part of a bigger community and being able to reproduce browser specific bugs in your test suite is probably a good argument, too.

There's more info about Playwright at https://playwright.dev/

**PS:** Also it might be possible to [test on external devices](https://github.com/microsoft/playwright/issues/1122) one day.

**Comment by matthewmcgarvey** [comment]
I'm going to close this issue because I'm fairly certain this will not be happening at least anytime soon.

I do want to explain why, though:

At the time this issue was made, we were using a [specific commit](https://github.com/luckyframework/lucky_flow/blob/26ebd2e04b71880f554610e5df9fd7df75892c8b/shard.yml#L12-L14) of https://github.com/ysbaddaden/selenium-webdriver-crystal and including a chromedriver binary in the library. We found that the library was not being actively maintained which meant that LuckyFlow had issues that we could not solve without forking the library or migrating.

This issue was made when marionette only supported FireFox and LuckyFlow only supported Chrome. The maintainers **at that time** did not feel it was worth it to make that migration. I was not a maintainer of Lucky at that point but I had run into issues with the selenium library we were using. Seeing that the library implemented the old standard, I wrote a [new selenium library](https://github.com/matthewmcgarvey/selenium.cr) that fully implements the [W3C Webdriver Standard](https://www.w3.org/TR/webdriver1/). This library supported Chrome before marionette did and we migrated to it. I also wrote a [library for maintaining webdrivers](https://github.com/matthewmcgarvey/webdrivers.cr) that we added to drop the shipped chromedriver binary.

I actively maintain this library and the libraries it uses so there's no worry for me about the libraries becoming stale. In fact, we recently refactored LuckyFlow to be able to support different browsers in https://github.com/luckyframework/lucky_flow/pull/113.

Thinking about why marionette wasn't adopted for LuckyFlow, I think it was a combination of branding and misunderstanding on both sides. The issue says that marionette doesn't rely on java where our library did but that wasn't true, both were written in pure crystal. The differences between our current selenium library and marionette is largely API differences as they both implement the W3C standard. With regards to branding, I believe marionette wasn't looked into as closely as it maybe should have been because "selenium" was a known and trusted brand name while "marionette" was unfamiliar even though they both do the same thing.

Anyways, I hope that is all understandable and we can definitely keep up the conversation in discord.

And regarding Playwright, @alexanderadam, the crystal forum post was my first introduction to it, and it seems really interesting. Unfortunately, I don't think we're going to go with it. The good news, though, is that LuckyFlow really doesn't do all that much! If you wanted to use Playwright with a lucky app it wouldn't be difficult at all to take out LuckyFlow. You could even write a thin library that adds in some Lucky integration. If you wanted to take a shot at it, I'd be glad to help you 😄
